name: 8b8tCore
main: me.txmc.core.Main
version: 1.4.7
author: 254n_m, agarciacorte
description: All the bullshit for 6b6t
api-version: 1.20
folia-supported: true
softdepend:
  - VotifierPlus
commands:
  msg:
    aliases: [message, whisper, tell, w, t]
  reply:
    aliases: [r]
  ignore:
  togglechat:
  unignore:
  ignorelist:
  tpa:
  tpahere:
  tpayes:
    aliases: [tpaaccept]
  tpano:
    aliases: [tpadeny]
  tpacancel:
  home:
  sethome:
  delhome:
  back:
  hotspot:
  lef:
  discord:
  matrix:
  help:
  open:
  say:
  spawn:
  speed:
  uptime:
  world:
  vote:
  tpsinfo:
  repair:
  nick:
    aliases: [nickname, setnick]
  ic:
    aliases: [itemcolor, setcolor]
  nc:
    aliases: [nickcolor, namecolor]
  rename:
  sign:
  togglejoinmessages:
    aliases: [jm, tjm]
  shadowmute:
    aliases: [mute, sm]
  vanish:
    aliases: [v]
  clearentities:
    aliases: [ce]
  gmc:
  gmsp:
  gms:
  suicide:
    aliases: [illegal, illegalevent, kit, kits, dupe]
  table:
permissions:
  8b8tcore.viewdistance.default:
    description: Permission for the default view distance
    default: true
  8b8tcore.viewdistance.4:
    description: Permission to set a view distance of 4 chunks
    default: false
  8b8tcore.viewdistance.6:
    description: Permission to set a view distance of 6 chunks
    default: false
  8b8tcore.viewdistance.8:
    description: Permission to set a view distance of 8 chunks
    default: false
  8b8tcore.viewdistance.16:
    description: Permission to set a view distance of 16 chunks
    default: false
  8b8tcore.viewdistance.32:
    description: Permission to set a view distance of 32 chunks
    default: false
  8b8tcore.simulationdistance.default:
    description: Permission for the default simulation distance
    default: true
  8b8tcore.simulationdistance.4:
    description: Permission to set a simulation distance of 4 chunks
    default: false
  8b8tcore.simulationdistance.6:
    description: Permission to set a simulation distance of 6 chunks
    default: false
  8b8tcore.simulationdistance.8:
    description: Permission to set a simulation distance of 8 chunks
    default: false
  8b8tcore.simulationdistance.16:
    description: Permission to set a simulation distance of 16 chunks
    default: false
  8b8tcore.simulationdistance.32:
    description: Permission to set a simulation distance of 32 chunks
    default: false
  8b8tcore.tpsinfo:
    description: Permission to show TPS information
    default: false
  8b8tcore.prefix.bot:
    description: Nametag Prefix for VERIFIED BOTS
    default: false
  8b8tcore.prefix.dev:
    description: Nametag Prefix for DEV
    default: false