name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 8b8tCore
          path: target/*.jar

